apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f3ywd4n25-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f3ywd4n25-python 
  name: f3ywd4n25-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: f3ywd4n25-python 
