apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: f3ywd4n25-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-5871366109.swbu.p3.openshiftapps.com/rhtap/rhtap-qe:99e7b9f432c1cf281bf34eb7557b44a2cfed98d6@sha256:a8dce41379b2fc0a43c4e815c9397c9f5057730195bd8047a527ffe07cf0f578
          name: container-image
